### ISSUE TITLE
Please add my credit back on ur website source code

### ISSUE THREAD

**Issue by Kuuuuuuuu** [nevzra/nevzra#2]
![orca-image-53723962](https://user-images.githubusercontent.com/69802296/213956260-6529a397-fd86-4ac1-901e-e5e9124e4eaa.jpeg)
![Screenshot_2023-01-23-09-27-38-67_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/69802296/213956320-4ed73162-8c0c-41f3-9f13-3e7fc73346e3.jpg)
![Screenshot_2023-01-23-09-27-50-23_e4424258c8b8649f6e67d283a50a2cbc](https://user-images.githubusercontent.com/69802296/213956324-9622f9d1-d3f3-4856-bdd2-8bbca1cc1355.jpg)

At least add my credit back or just rewrite some of code please respond me back!

**Comment by nevze** [comment]
ah okay sorry, im using auto replace

**Comment by Kuuuuuuuu** [comment]
> ah okay sorry, im using auto replace

No problem bro. my website sources code is free to use but it need to keep my credit back so don't worries

**Comment by nevze** [comment]
> > ah okay sorry, im using auto replace
> 
> No problem bro. my website sources code is free to use but it need to keep my credit back so don't worries

okay, ill change later after working

**Comment by nevze** [comment]
done

**Comment by Kuuuuuuuu** [comment]
> done

😊 Thanks 👍🙏
